### ISSUE TITLE
Import "List of Oddities" to issue tracker

### ISSUE THREAD

**Issue by kkartaltepe** [projectbuildcraft/buildcraft#1]
I don't know if you guys already have a different tracker outside of github but it would probably be nice to move those issues here so you can keep track and log the issues you have closed and their solutions (ref to the commit). I would do this but I have just glanced at your code so maybe they have already been solved?

**Comment by wjmelements** [comment]
List of Oddities was our planning discussion. The file is old and should probably be removed. Thanks for reminding us about it, though if you were to try to break our code, looking at the things we were afraid of may be a good start.

**Comment by kkartaltepe** [comment]
I would say that removing that is a good solution but maybe you shouldn't close the issue till you actually do remove it! (unless this issue is a non-issue to you in which case it you believe it warrants no code changes and be closed without any.) but this is all dependent on if you actually want to track issues lol.

**Comment by wjmelements** [comment]
We could track issues through here because this is a cool feature, but the issue was closed because it will not influence the code. Most of our issues so far have been self-reported via facebook chat and fixed the same day. If there is a flood of issues from beta testers, then we should migrate them to a checklist system here.
